### PR TITLE
Wait for workers before destroying the pool

### PR DESCRIPTION
**Pull request by ayllon**
Possible race condition otherwise, reported by tsan

### CODE REVIEW

**Comment by FlorianDubath** [comment]
A question: we have the worker each in a thread, then the join() which is waiting for the execution to complete: in this condition do we still need the line above waitWorkers(m_worker_done_flags, m_empty_queue_wait_time); which role was to wait for the detached worker through the done flags

**Comment by ayllon** [comment]
My intention was to get rid of that, indeed, but it is also used when we call `block()`. I assume the intention was to be able to empty the queue without destroying the workers, so the pool could be reused. That's why I have left it in place.

**Comment by FlorianDubath** [comment]
Shouldn't we put also a join in the block and then rise a flag so the destructor skip the join?

**Comment by ayllon** [comment]
I think `block` is not intended to end the pool. If you check, the wait in block is 

`waitWorkers(m_worker_sleeping_flags, m_empty_queue_wait_time);`

It waits for the workers to be sleeping (doing nothing and nothing to do). It does *not* wait for them to exit.

While for the destructor

` waitWorkers(m_worker_done_flags, m_empty_queue_wait_time);`

It waits for the workers to be outside the loop, so finishing.

So I do not think `block` should  `join` the workers.

**Comment by FlorianDubath** [comment]
Sorry didn't see this was used on different flags...

**Review by FlorianDubath — APPROVED** [review]

**Pull request merged**
